# https://github.com/lowlighter/metrics#-documentation
name: Metrics
on:
  # https://crontab.guru/#0_0_*_*_*
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS }}

          # Options
          user: TiagoDanin
          template: classic
          base: header, activity, repositories
          base_hireable: yes
          config_timezone: America/Belem
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: languages, languages-graphs, editors-graphs, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: TiagoDanin
          plugin_languages: yes
          plugin_languages_analysis_timeout: 45
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_ignored: html, css, csharp, shaderlab, hlsl
          plugin_languages_colors: github
          plugin_languages_limit: 7
          plugin_languages_recent_days: 100
          plugin_languages_recent_load: 300
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_achievements: true
          plugin_achievements_limit: 5
          plugin_posts: true
          plugin_posts_source: dev.to
          plugin_posts_user: TiagoDanin
          plugin_posts_limit: 3
          repositories_affiliations: owner, collaborator
          repositories_forks: false
